**Note**: Click on "*Kernel*" > "*Restart Kernel and Clear All Outputs*" in [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) *before* reading this notebook to reset its output. If you cannot run this file on your machine, you may want to open it [in the cloud <img height="12" style="display: inline-block" src="../static/link/to_mb.png">](https://mybinder.org/v2/gh/webartifex/intro-to-python/develop?urlpath=lab/tree/11_classes/04_content.ipynb).

# Chapter 11: Classes & Instances (continued)

In this fourth part of the chapter, we finalize our `Vector` and `Matrix` classes. As both `class` definitions have become rather lengthy, we learn how we to organize them into a Python package and import them in this Jupyter notebook. 

## Packages vs. Modules

In [Chapter 2 <img height="12" style="display: inline-block" src="../static/link/to_nb.png">](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/develop/02_functions/02_content.ipynb#Local-Modules-and-Packages), we introduce the concept of a Python module that is imported with the `import` statement. Essentially, a **module** is a single plain text \*.py file on disk that contains Python code (e.g., [*sample_module.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/02_functions/sample_module.py) in [Chapter 2's folder <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/02_functions)).

Conceptually, a **package** is a generalization of a module whose code is split across several \*.py to achieve a better organization of the individual parts. The \*.py files are stored within a folder (e.g., [*sample_package* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/11_classes/sample_package) in [Chapter 11's folder <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/11_classes)). In addition to that, a "*\_\_init\_\_.py*" file that may be empty must be put inside the folder. The latter is what the Python interpreter looks for to decide if a folder is a package or not.

Let's look at an example with the final version of our `Vector` and `Matrix` classes.

`!pwd` shows the location of this Jupyter notebook on the computer you are running [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) on: It is the local equivalent of [Chapter 11's folder <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/11_classes) in this book's [GitHub repository <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python).

In [1]:
!pwd

/home/webartifex/repos/intro-to-python/11_classes


`!ls` lists all the files and folders in the current location: These are Chapter 11's Jupyter notebooks (i.e., the \*.ipynb files) and the [*sample_package* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/11_classes/sample_package) folder. 

In [2]:
!ls

00_content.ipynb    02_content.ipynb  04_content.ipynb
01_exercises.ipynb  03_content.ipynb  sample_package


If we run `!ls` with the `sample_package` folder as the argument, we see the folder's contents: Four \*.py files. Alternatively, you can use [JupyterLab' File Browser](https://jupyterlab.readthedocs.io/en/stable/user/interface.html?highlight=file%20browser#left-sidebar) on the left to navigate into the package.

In [3]:
!ls sample_package

__init__.py  matrix.py	utils.py  vector.py


The package is organized such that the [*matrix.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/matrix.py) and [*vector.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/vector.py) modules each define just one class, `Matrix` and `Vector`. That is intentional as both classes consist of several hundred lines of code and comments.

The [*utils.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/utils.py) module contains code that is shared by both classes. Such code snippets are commonly called "utilities" or "helpers," which explains the module's name.

Finally, the [*\_\_init\_\_.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/__init__.py) file contains mostly meta information and defines what objects should be importable from the package's top level.

With the `import` statement, we can import the entire package just as we would import a module from the [standard library <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/index.html).

In [4]:
import sample_package as pkg

The above cell runs the code in the [*\_\_init\_\_.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/__init__.py) file from top to bottom, which in turn runs the [*matrix.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/matrix.py), [*utils.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/utils.py), and [*vector.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/vector.py) modules (cf., look at the `import` statements in the four \*.py files to get the idea). As both [*matrix.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/matrix.py) and [*vector.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/vector.py) depend on each other (i.e., the `Matrix` class needs the `Vector` class to work and vice versa), understanding the order in that the modules are executed is not trivial. Without going into detail, we mention that Python guarantees that each \*.py file is run only once and figures out the order on its own. If Python is unable to do that, for example, due to unresolvable cirular imports, it aborts with an `ImportError`.

Below, `pkg` is an object of type `module` ...

In [5]:
pkg

<module 'sample_package' from '/home/webartifex/repos/intro-to-python/11_classes/sample_package/__init__.py'>

In [6]:
type(pkg)

module

... and we use the built-in [dir() <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/functions.html#dir) function to check what attributes `pkg` comes with.

In [7]:
dir(pkg)

['Matrix',
 'Vector',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'matrix',
 'utils',
 'vector']

The package's meta information and documentation are automatically parsed from the [*\_\_init\_\_.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/__init__.py) file.

In [8]:
help(pkg)

Help on package linear_algebra_tools:

NAME
    linear_algebra_tools - This package provides linear algebra functionalities.

DESCRIPTION
    The package is split into three modules:
    - matrix: defines the Matrix class
    - vector: defines the Vector class
    - utils: defines the norm() function that is shared by Matrix and Vector
             and package-wide constants
    
    The classes implement arithmetic operations involving vectors and matrices.
    
    See the docstrings in the modules and classes for further info.

PACKAGE CONTENTS
    matrix
    utils
    vector

CLASSES
    builtins.object
        sample_package.matrix.Matrix
        sample_package.vector.Vector
    
    class Matrix(builtins.object)
     |  Matrix(data)
     |  
     |  An m-by-n-dimensional matrix from linear algebra.
     |  
     |  All entries are converted to floats, or whatever is set in the typing attribute.
     |  
     |  Attributes:
     |      storage (callable): data type used to store t

The meta information could also be accessed separately and individually.

In [9]:
pkg.__name__

'linear_algebra_tools'

In [10]:
pkg.__version__  # follows the semantic versioning format

'0.1.0'

We create `Vector` and `Matrix` instances in the usual way by calling the `Vector` and `Matrix` classes from the package's top level.

In [11]:
pkg.Vector([1, 2, 3])

Vector((1.0, 2.0, 3.0))

In [12]:
pkg.Matrix([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,), (7.0, 8.0, 9.0,)))

A common practice by package authors is to put all the objects on the package's top level that they want the package users to work with directly. That is achieved via the `import` statements in the [*\_\_init\_\_.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/__init__.py) file.

However, users can always reach into a package and work with its internals.

For example, the `Vector` and `Matrix` classes are also available via their **qualified name** (cf., [PEP 3155 <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://www.python.org/dev/peps/pep-3155/)): First, we access the `vector` and `matrix` modules on `pkg`, and then the `Vector` and `Matrix` classes on the modules.

In [13]:
pkg.vector.Vector

sample_package.vector.Vector

In [14]:
pkg.matrix.Matrix

sample_package.matrix.Matrix

Also, let's import the [*utils.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/utils.py) module with the `norm()` function into the global scope. As this function is integrated into the `Vector.__abs__()` and `Matrix.__abs__()` methods, there is actually no need to work with it explicitly.

In [15]:
from sample_package import utils

In [16]:
help(utils.norm)

Help on function norm in module sample_package.utils:

norm(vec_or_mat)
    Calculate the Frobenius or Euclidean norm of a matrix or vector.
    
    Find more infos here: https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm
    
    Args:
        vec_or_mat (Vector / Matrix): object whose entries are squared and summed up
    
    Returns:
        norm (float)
    
    Example Usage:
        As Vector and Matrix objects are by design non-empty sequences,
        norm() may be called, for example, with `[3, 4]` as the argument:
        >>> norm([3, 4])
        5.0



Many tutorials on the internet begin by importing "everything" from a package into the global scope with `from ... import *`.

That is commonly considered a *bad* practice as it may overwrite already existing variables. However, if the package's [*\_\_init\_\_.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/__init__.py) file defines an `__all__` attribute, a `list` with all the names to be "exported," the **star import** is safe to be used, in particular, in *interactive* sessions like Jupyter notebooks. We emphasize that the star import should *not* be used *within* packages and modules as then it is not directly evident from a name where the corresponding object is defined.

For more best practices regarding importing we refer to, among others, [Google's Python Style Guide](https://google.github.io/styleguide/pyguide.html#22-imports).

The following `import` statement makes the `Vector` and `Matrix` classes available in the global scope.

In [17]:
from sample_package import *

In [18]:
Vector

sample_package.vector.Vector

In [19]:
Matrix

sample_package.matrix.Matrix

For further information on modules and packages, we refer to the [official tutorial <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/tutorial/modules.html).

## The final `Vector` and `Matrix` Classes

The final implementations of the `Vector` and `Matrix` classes are in the [*matrix.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/matrix.py) and [*vector.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/vector.py) files: They integrate all of the functionalities introduced in this chapter. In addition, the code is cleaned up and fully documented, including examples of common usages.

We strongly suggest the eager student go over the files in the [*sample_package* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/tree/develop/11_classes/sample_package) in detail at some point to understand what well-written and (re-)usable code looks like.

In [20]:
v = Vector([1, 2, 3])

In [21]:
v

Vector((1.0, 2.0, 3.0))

In [22]:
type(v)

sample_package.vector.Vector

In [23]:
m = Matrix([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [24]:
m

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,), (7.0, 8.0, 9.0,)))

In [25]:
type(m)

sample_package.matrix.Matrix

Furthermore, the classes are designed for easier maintenence in the long-run.

For example, the `Matrix/Vector.storage` and `Matrix/Vector.typing` class attributes replace the "hard coded" [tuple() <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/functions.html#func-tuple) and [float() <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/functions.html#float) built-ins in the `.__init__()` methods: As `self.storage` and `self.typing` are not defined on the *instances*, Python automatically looks them up on the *classes*.

In [26]:
Vector.storage

tuple

In [27]:
Vector.typing

float

In [28]:
Vector.__init__??

Signature: Vector.__init__(self, data)
Source:   
    def __init__(self, data):
        """Create a new vector.

        Args:
            data (sequence): the vector's entries

        Raises:
            ValueError: if no entries are provided

        Example Usage:
            >>> Vector([1, 2, 3])
            Vector((1.0, 2.0, 3.0))

            >>> Vector(range(3))
            Vector((0.0, 1.0, 2.0))
        """
        self._entries = self.storage(self.typing(x) for x in data)
        if len(self) == 0:
            raise ValueError("a vector must have at least one entry")
File:      ~/repos/intro-to-python/11_classes/sample_package/vector.py
Type:      function


Both `Matrix/Vector.storage` and `Matrix/Vector.typing` themselves reference the `DEFAULT_ENTRIES_STORAGE` and `DEFAULT_ENTRY_TYPE` constants in the [*utils.py* <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com/webartifex/intro-to-python/blob/develop/11_classes/sample_package/utils.py) module. This way, we could, for example, change only the constants and thereby also change how the `._entries` are stored internally in both classes. Also, this single **[single source of truth <img height="12" style="display: inline-block" src="../static/link/to_wiki.png">](https://en.wikipedia.org/wiki/Single_source_of_truth)** ensures that both classes are consistent with each other at all times.

In [29]:
utils.DEFAULT_ENTRIES_STORAGE

tuple

In [30]:
utils.DEFAULT_ENTRY_TYPE

float

For the same reasons, we also replace the "hard coded" references to the `Vector` and `Matrix` classes within the various methods.

Every instance object has an automatically set `.__class__` attribute referencing its class.

In [31]:
m.__class__

sample_package.matrix.Matrix

Of course, we could also use the [type() <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/functions.html#type) built-in instead.

In [32]:
type(m)

sample_package.matrix.Matrix

So, for example, the `Matrix.transpose()` method makes a `self.__class__(...)` instead of a `Matrix(...)` call.

In [33]:
Matrix.transpose??

Signature: Matrix.transpose(self)
Source:   
    def transpose(self):
        """Switch the rows and columns of a Matrix.

        Returns:
            matrix (Matrix)

        Example Usage:
            >>> m = Matrix([(1, 2), (3, 4)])
            >>> m
            Matrix(((1.0, 2.0,), (3.0, 4.0,)))
            >>> m.transpose()
            Matrix(((1.0, 3.0,), (2.0, 4.0,)))
        """
        return self.__class__(zip(*self._entries))
File:      ~/repos/intro-to-python/11_classes/sample_package/matrix.py
Type:      function


Whenever we need a `str` representation of a class's name, we use the `.__name__` attribute on the class, ...

In [34]:
Matrix.__name__

'Matrix'

... or access it via the `.__class__` attribute on an instance.

In [35]:
m.__class__.__name__

'Matrix'

For example, the `.__repr__()` and `.__str__()` methods make use of that.

In [36]:
Matrix.__repr__??

Signature: Matrix.__repr__(self)
Source:   
    def __repr__(self):
        """Text representation of a Matrix."""
        name = self.__class__.__name__
        args = ", ".join(
            "(" + ", ".join(repr(c) for c in r) + ",)" for r in self._entries
        )
        return f"{name}(({args}))"
File:      ~/repos/intro-to-python/11_classes/sample_package/matrix.py
Type:      function


In order to not have to "hard code" the name of *another* class (e.g., the `Vector.as_matrix()` method references the `Matrix` class), we apply the following "hack:" First, we store a reference to the other class as a class attribute (e.g., `Matrix.vector_cls` and `Vector.matrix_cls`), and then reference that attribute within the methods, just like `.storage` and `.typing` above.

In [37]:
Matrix.vector_cls

sample_package.vector.Vector

In [38]:
Vector.matrix_cls

sample_package.matrix.Matrix

As an example, the `Vector.as_matrix()` method makes a `self.matrix_cls(...)` instead of a `Matrix(...)` call.

In [39]:
Vector.as_matrix??

Signature: Vector.as_matrix(self, *, column=True)
Source:   
    def as_matrix(self, *, column=True):
        """Get a Matrix representation of a Vector.

        Args:
            column (bool): if the vector is interpreted as a
                column vector or a row vector; defaults to True

        Returns:
            matrix (matrix.Matrix)

        Example Usage:
            >>> v = Vector([1, 2, 3])
            >>> v.as_matrix()
            Matrix(((1.0,), (2.0,), (3.0,)))
            >>> v.as_matrix(column=False)
            Matrix(((1.0, 2.0, 3.0,)))
        """
        if column:
            return self.matrix_cls([x] for x in self)
        return self.matrix_cls([(x for x in self)])
File:      ~/repos/intro-to-python/11_classes/sample_package/vector.py
Type:      function


For completeness sake, we mention that in the final `Vector` and `Matrix` classes, the `.__sub__()` and `.__rsub__()` methods use the negation operator implemented in `.__neg__()` and then dispatch to `.__add__()` instead of implementing the subtraction logic themselves.

## "Real-life" Experiment

Let's do some math with bigger `Matrix` and `Vector` instances.

In [40]:
import random

In [41]:
random.seed(42)

We initialize `m` as a $100x50$ dimensional `Matrix` with random numbers in the range between `0` and `1_000`.

In [42]:
m = Matrix((1_000 * random.random() for _ in range(50)) for _ in range(100))

We quickly lose track with all the numbers in the `Matrix`, which is why we implemented the `__str__()` method as a summary representation.

In [43]:
m

Matrix(((639.4267984578837, 25.010755222666937, 275.02931836911927, 223.21073814882274, 736.4712141640124, 676.6994874229113, 892.1795677048455, 86.93883262941615, 421.9218196852704, 29.797219438070343, 218.63797480360336, 505.3552881033624, 26.535969683863627, 198.8376506866485, 649.8844377795232, 544.9414806032166, 220.4406220406967, 589.2656838759087, 809.4304566778267, 6.498759678061017, 805.8192518328079, 698.1393949882269, 340.25051651799185, 155.47949981178155, 957.2130722067812, 336.59454511262675, 92.7458433801479, 96.71637683346401, 847.4943663474597, 603.7260313668911, 807.1282732743801, 729.7317866938179, 536.2280914547007, 973.1157639793706, 378.5343772083535, 552.040631273227, 829.4046642529948, 618.5197523642461, 861.7069003107772, 577.352145256762, 704.5718362149235, 45.82438365566222, 227.89827565154687, 289.38796360210716, 79.79197692362749, 232.79088636103018, 101.00142940972911, 277.97360311009214, 635.6844442644002, 364.8321789700842,), (370.18096711688264, 209.507

In [44]:
print(m)

Matrix((639.4267984578837, ...), ..., (..., 353.85334437419004))[100x50]


Similarily, `v` is now a `Vector` with $50$ entries.

In [45]:
v = Vector(1_000 * random.random() for _ in range(50))

In [46]:
v

Vector((129.7131375543026, 562.6343376666077, 519.7058001844938, 631.8576074968361, 492.50445371851595, 179.90723165619127, 609.4057577306154, 708.5870675033931, 979.2576595660704, 1.580917225831202, 23.986797518176004, 625.4607423896532, 117.92572392127187, 848.0697885701867, 799.5643512555062, 998.9870072501308, 414.04113952437183, 333.7922569338235, 560.4155049178265, 637.5035435880566, 11.297267978029769, 201.1871389300902, 281.62670325053864, 790.1955028462116, 307.77254924389706, 506.6896270960092, 323.9238393830701, 6.131262435292828, 685.8357886469579, 341.36158523000273, 724.3966428110118, 615.9933429964842, 29.117381811460618, 175.62908823799773, 330.51483209301, 337.936855273543, 672.4729573660214, 916.1630531735751, 797.2543838289249, 645.6522206645749, 481.4955231203607, 627.2004877076889, 892.0583267899182, 536.9675449723645, 335.10965453438513, 783.9890332085388, 413.95306533418574, 742.5846461655369, 835.1057359656187, 299.3437466393607))

In [47]:
print(v)

Vector(129.7131375543026, ..., 299.3437466393607)[50]


The arithmetic works as before.

In [48]:
w = m * v

In [49]:
print(w)

Vector(11378937.3105893, ..., 13593029.305789862)[100]


We can multiply `m` with its transpose or the other way round.

In [50]:
n = m * m.transpose()

In [51]:
print(n)

Matrix((14370711.265265431, ...), ..., (..., 16545418.239505699))[100x100]


In [52]:
o = m.transpose() * m

In [53]:
print(o)

Matrix((32618511.50703142, ...), ..., (..., 32339164.77803234))[50x50]


## Comparison with [numpy](https://www.numpy.org/)

We started out in this chapter by realizing that Python provides us no good data type to model a vector $\vec{x}$ or a matrix $\bf{A}$. Then, we built up two custom data types, `Vector` and `Matrix`, that wrap a simple `tuple` object for $\vec{x}$ and a `tuple` of `tuple`s for $\bf{A}$ so that we can interact with their `._entries` in a "natural" way, which is similar to how we write linear algebra tasks by hand. By doing this, we extend Python with our own little "dialect" or **[domain-specific language <img height="12" style="display: inline-block" src="../static/link/to_wiki.png">](https://en.wikipedia.org/wiki/Domain-specific_language)** (DSL).

If we feel like sharing our linear algebra library with the world, we could easily do so on either [GitHub <img height="12" style="display: inline-block" src="../static/link/to_gh.png">](https://github.com) or [PyPI](https://pypi.org). However, for the domain of linear algebra this would be rather pointless as there is already a widely adopted library with [numpy](https://www.numpy.org/) that not only has a lot more features than ours but also is implemented in C, which makes it a lot faster with big data.

Let's model the example in the [first part <img height="12" style="display: inline-block" src="../static/link/to_nb.png">](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/develop/11_classes/00_content.ipynb#Example:-Vectors-&-Matrices) with both [numpy](https://www.numpy.org/) and our own DSL and compare them.

In [54]:
x = (1, 2, 3)
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [55]:
A * x

TypeError: can't multiply sequence by non-int of type 'tuple'

The creation of vectors and matrices is similar to our DSL. However, numpy uses the more general concept of an **n-dimensional array** (i.e., the `ndarray` type) where a vector is only a special case of a matrix and a matrix is yet another special case of an even higher dimensional structure.

In [56]:
import numpy as np

In [57]:
x_arr = np.array(x)
A_arr = np.array(A)

In [58]:
x_vec = Vector(x)
A_mat = Matrix(A)

The text representations are very similar. However, [numpy](https://www.numpy.org/)'s `ndarray`s keep the entries as `int`s while our `Vector` and `Matrix` objects contain `float`s.

In [59]:
x_arr

array([1, 2, 3])

In [60]:
x_vec

Vector((1.0, 2.0, 3.0))

In [61]:
A_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
A_mat

Matrix(((1.0, 2.0, 3.0,), (4.0, 5.0, 6.0,), (7.0, 8.0, 9.0,)))

[numpy](https://www.numpy.org/)'s `ndarray`s come with a `.shape` instance attribute that returns a `tuple` with the dimensions ...

In [63]:
x_arr.shape

(3,)

In [64]:
A_arr.shape

(3, 3)

... while `Matrix` objects come with `.n_rows` and `.n_cols` properties.

In [65]:
A_mat.n_rows, A_mat.n_cols

(3, 3)

The built-in [len() <img height="12" style="display: inline-block" src="../static/link/to_py.png">](https://docs.python.org/3/library/functions.html#len) function does not return the number of entries in an `ndarray` but the number of the rows instead. This is equivalent to the first element in the `.shape` attribute.

In [66]:
len(x_arr)

3

In [67]:
len(x_vec)

3

In [68]:
len(A_arr)

3

In [69]:
len(A_mat)

9

The `.transpose()` method also exists for `ndarray`s.

In [70]:
A_arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [71]:
A_mat.transpose()

Matrix(((1.0, 4.0, 7.0,), (2.0, 5.0, 8.0,), (3.0, 6.0, 9.0,)))

To perform matrix-matrix, matrix-vector, or vector-matrix multiplication in [numpy](https://www.numpy.org/), we use the `.dot()` method. If we use the `*` operator with `ndarray`s, an *entry-wise* multiplication is performed.

In [72]:
A_arr.dot(x_arr)

array([14, 32, 50])

In [73]:
A_arr * x_arr

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [74]:
A_mat * x_vec

Vector((14.0, 32.0, 50.0))

Scalar multiplication, however, works as expected.

In [75]:
10 * x_arr

array([10, 20, 30])

In [76]:
10 * x_vec

Vector((10.0, 20.0, 30.0))

Because we implemented our classes to support the sequence protocol, [numpy](https://www.numpy.org/)'s *one*-dimensional `ndarray`s are actually able to work with them: The `*` operator is applied on a per-entry basis.

In [77]:
x_arr + x_vec

array([2., 4., 6.])

In [78]:
x_arr * x_vec

array([1., 4., 9.])

In [79]:
A_arr + A_mat

ValueError: operands could not be broadcast together with shapes (3,3) (9,) 

We conclude that it is rather easy to extend Python in a way that makes the resulting application code read like core Python again. As there are many well established third-party packages out there, it is unlikely that we have to implement a fundamental library ourselves. Yet, we can apply the concepts introduced in this chapter to organize the code in the applications we write.